---
- name: Install libselinux-python
  become: true
  ansible.builtin.yum:
    name: libselinux-python
    state: present

- name: Copy the EPEL repository definition
  become: true
  ansible.builtin.file:
    src: epel.repo 
    dest: /etc/yum.repos.d/epel.repo
    mode: 0644

- name: Create the GPG key for EPEL
  become: true
  ansible.builtin.file:
    src: RPM-GPG-KEY-EPEL-6 
    dest: /etc/pki/rpm-gpg
    mode: 0644
